apiVersion: cilium.io/v2
kind: CiliumNetworkPolicy
metadata:
  creationTimestamp: "2025-09-14T01:53:17Z"
  generation: 1
  labels:
    created-by: ppcs-nsm
    managed-by: quarkus-app
  name: gb7yp-9meitm
  namespace: satish-kaushik-t45d6
  resourceVersion: "17340356"
  uid: 57ba81b5-daf8-4e8c-8887-9377ead81a67
spec:
  endpointSelector:
    matchLabels:
      serial: GB7YP
  ingress:
  - fromCIDR:
    - 45.248.67.9/32
    toPorts:
    - ports:
      - endPort: 0
        port: "80"
        protocol: TCP
status:
  conditions:
  - lastTransitionTime: "2025-09-14T01:53:17Z"
    message: Policy validation succeeded
    status: "True"
    type: Valid